// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShorturlClient is the client API for Shorturl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShorturlClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
}

type shorturlClient struct {
	cc grpc.ClientConnInterface
}

func NewShorturlClient(cc grpc.ClientConnInterface) ShorturlClient {
	return &shorturlClient{cc}
}

func (c *shorturlClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/shorturl.Shorturl/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorturlServer is the server API for Shorturl service.
// All implementations must embed UnimplementedShorturlServer
// for forward compatibility
type ShorturlServer interface {
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	mustEmbedUnimplementedShorturlServer()
}

// UnimplementedShorturlServer must be embedded to have forward compatible implementations.
type UnimplementedShorturlServer struct {
}

func (UnimplementedShorturlServer) Create(context.Context, *CreateRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShorturlServer) mustEmbedUnimplementedShorturlServer() {}

// UnsafeShorturlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShorturlServer will
// result in compilation errors.
type UnsafeShorturlServer interface {
	mustEmbedUnimplementedShorturlServer()
}

func RegisterShorturlServer(s grpc.ServiceRegistrar, srv ShorturlServer) {
	s.RegisterService(&Shorturl_ServiceDesc, srv)
}

func _Shorturl_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorturlServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorturl.Shorturl/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorturlServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shorturl_ServiceDesc is the grpc.ServiceDesc for Shorturl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shorturl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shorturl.Shorturl",
	HandlerType: (*ShorturlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shorturl_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shorturl.proto",
}
